### ISSUE TITLE
Error 400

### ISSUE THREAD

**Issue by michael-milette** [codama-dev/ai-docs-and-comments#1]
Does not seem to work anymore. I keep getting Error 400.

**Comment by ncamaa** [comment]
Thanks @michael-milette, I just checked and it seems to work. Please go to your settings and ensure everything is in place:
`CMD+Shift+P` and then `AI Docs & Comments: Go to Settings`
<img width="512" alt="image" src="https://github.com/codama-dev/ai-docs-and-comments/assets/25122974/8fe7106c-66a7-4442-b086-3de12823cfc9">
More info [here](https://github.com/codama-dev/ai-docs-and-comments#extension-settings) 

If you're still getting errors please share your logs and/or some screenshots.
Thanks!

**Comment by michael-milette** [comment]
Hi @ncamaa ,

I just re-installed the extension and configured the settings, as per your documentation. However, I am still getting the error. I am developing in PHP. Here are some screenshots:

If I use the **Create documentation** option:
<img width="400" alt="image" src="https://github.com/codama-dev/ai-docs-and-comments/assets/3808579/555b6461-805e-465c-8687-8b5840ff2fb5">

If I use the **Add Comments** option:
<img width="400" alt="image" src="https://github.com/codama-dev/ai-docs-and-comments/assets/3808579/70911dc9-7684-4561-b756-c3b61a0276bb">

In both cases, once I get the error, it completely deletes the selected function and replaces it all with the following line:

    // problem generating documentation

If I am not paying attention and save, my code could be gone forever 😥

It took me a while but I finally figured out what works and what does not.

Here is an example of a function where your extension actually works fine:

    function gettime($txt) {
        return $txt . time();
    }

However, your extension deletes my code and generates the error when I use it on the following code:

    function gettime($glossaryData) {
        return $glossaryData . time();
    }

Looks like it could not figure out what data type the variable $glossaryData was and decided that nobody should have that code - including me! 😄

Hope you find this helpful.

Best regards,

Michael

**Comment by ncamaa** [comment]
Thanks for sharing. I'll look into it and get back to you 👍

**Comment by ncamaa** [comment]
@michael-milette 
Hey,

Thanks a lot for taking the time to outline the issues you're encountering with our extension. We really appreciate the detailed feedback and the effort you've put into troubleshooting.

After looking into the matter on our end, we couldn't replicate the error you've described when working with PHP. Our extension was mainly tested with JavaScript and TypeScript, so there might be some quirks when it comes to PHP.

Just a heads-up, using a free OpenAI API key might be causing these errors you're encountering. I have no affiliation with OpenAI; it's just that the extension seems to work best when paired with a premium OpenAI account. So, you might get some errors working with the free version API. 

Since this is an open-source, non-profit project, one of the best ways to help would be to fork the repository and submit a pull request with a fix if you're comfortable doing so. This would not only solve your issue but also benefit others who might be facing the same problem.

Cheers, and thanks again for helping us improve the extension.

Best regards,
Nadav
<img width="280" alt="image" src="https://github.com/codama-dev/ai-docs-and-comments/assets/25122974/809fd438-78ad-463a-b129-ae0fa6b30ad9">
<img width="1635" alt="image" src="https://github.com/codama-dev/ai-docs-and-comments/assets/25122974/2eec571a-4180-483c-891a-6915d02c4b53">

**Comment by ncamaa** [comment]
After looking into the matter on our end, we couldn't replicate the error you've described when working with PHP. Our extension was mainly tested with JavaScript and TypeScript, so there might be some quirks when it comes to PHP.

**Comment by michael-milette** [comment]
Hi @ncamaa ,

From what I can see from your screenshot,  you are testing using the scenario that I said works. Please try the example that I said does not work. It is the one where the function parameter is $glossaryData.

I tried it with both a free and a paid OpenAI account.

Best regards,

Michael

**Comment by ncamaa** [comment]
Hey Michael,

Thanks for pointing that out. I went back and tested specifically with the function that uses `$glossaryData` as a parameter. I've also attached some screenshots for reference.

Unfortunately, I still couldn't replicate the issue you're facing. This is puzzling, to say the least.

![image](https://github.com/codama-dev/ai-docs-and-comments/assets/25122974/5284ca8c-42e6-4f9e-aa5d-2fd690421224)
![image](https://github.com/codama-dev/ai-docs-and-comments/assets/25122974/98d10277-1e84-468f-bf58-b4b12c50392e)
![image](https://github.com/codama-dev/ai-docs-and-comments/assets/25122974/8c68e7fa-2895-48af-bfb1-3cae99311129)

If you're up for it, feel free to fork the repo and dig into the code. Any pull requests with fixes are more than welcome!

Cheers,
Nadav
